### ISSUE TITLE
Example snowflake tile on model page is a dead link

### ISSUE THREAD

**Issue by ibrahim-sowunmi** [SimplyWallSt/Company-Analysis-Model#13]
The Snowflake
The results of the checks in each of the 5 assessment criteria are presented visually in our Snowflake. The snowflake has been designed to present the results for a company as a visually intuitive summary in order to allow:

a quick "eyeball" scan of a particular stock, a group of stocks or the stockmarket as a whole;

visual comparisons of the results of our stock filters;

visual side by side comparisons of selected stocks using our "compare" feature;

consolidated view using our "portfolio" feature.

**Example Snowflake
Example Snowflake Tile**

Methodology behind generating the Snowflake

**Comment by AlBentley** [comment]
This was due to a server migration and the .png of the image needs to be lowercase. Thanks for spotting.

**Comment by tcarroll2** [comment]
Still a dead link, and so is the linked [PDF](https://simplywall.st/documents/Simply-Wall-St-The-Snowflake-explained.pdf)
