### ISSUE TITLE
10-year government bond rate US vs. Greece

### ISSUE THREAD

**Issue by hpbruna** [SimplyWallSt/Company-Analysis-Model#14]
I looks that in all 'value' calculations you take the US 10-year government bond rate. If you select e.g. Greece you'll have quite a lot of stocks that rate as 'value'. Wouldn't it be appropriate to take the Greek 1-year bond rate (4.80%) as the base for the calculation for Greek stocks?

**Comment by simplymatt** [comment]
Hi hbpruna, 

Thanks for the question.

We use the Greek 10-year bond rate for our valuation calculations, updated semi-annually. Our current rate for the Greek market is 4.9%. Our calculation methods have changed over time. If you have spotted any other information in our communications please let us know and we will have that fixed up.

Best,
Matt
